# fly.toml app configuration file generated for personalizedclothing on 2026-05-28T22:51:10Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "personalizedclothing"
primary_region = "scl"

[build]

  [build.args]
    VITE_API_URL = "https://personalizedclothingapi.fly.dev/api"
    VITE_GOOGLE_MAPS_API_KEY = "AIzaSyC3CrRhhTihyzGfuBxYtgNZsGWarlBkUe8"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
